import os
import pandokia.helpers.test_in_db as test_in_db

test_in_db.query['test_name'] = 'pdkrun_test_data/minipyt/*'

expected_results = [
    #  test_name,
    #       dict of values for equivalence
    #
    # remember the db access library automatically converts things that look like numbers to float

	( 'pdkrun_test_data/minipyt/assert_on_import_f',
		{ 'status' : 'F' } ),
	( 'pdkrun_test_data/minipyt/assert_on_import_p',
		{ 'status' : 'P' } ),
	( 'pdkrun_test_data/minipyt/attr.class_setup_exception',
		{ 'status' : 'E', 'tra_exception' : "Exception('ARF',)" } ),
	( 'pdkrun_test_data/minipyt/attr.not_shared.test_1',
		{ 'status' : 'P' } ),
	( 'pdkrun_test_data/minipyt/attr.not_shared.test_2',
		{ 'status' : 'P' } ),
	( 'pdkrun_test_data/minipyt/attr.not_shared',
		{ 'status' : 'P' } ),
	( 'pdkrun_test_data/minipyt/attr.setup_exception.test_1',
		{ 'status' : 'E' } ),
	( 'pdkrun_test_data/minipyt/attr.setup_exception.test_2',
		{ 'status' : 'E' } ),
	( 'pdkrun_test_data/minipyt/attr.setup_exception',
		{ 'status' : 'P' } ),
	( 'pdkrun_test_data/minipyt/attr.shared.test_1',
		{ 'status' : 'P' } ),
	( 'pdkrun_test_data/minipyt/attr.shared.test_2',
		{ 'status' : 'P' } ),
	( 'pdkrun_test_data/minipyt/attr.shared',
		{ 'status' : 'P' } ),
	( 'pdkrun_test_data/minipyt/attr',
		{ 'status' : 'P', 'tda_module' : 'this is a module tda' } ),
	( 'pdkrun_test_data/minipyt/class_1.init_f',
		{ 'status' : 'E' } ),
	( 'pdkrun_test_data/minipyt/class_1.init_p',
		{ 'status' : 'P' } ),
	( 'pdkrun_test_data/minipyt/class_1',
		{ 'status' : 'P' } ),
	( 'pdkrun_test_data/minipyt/class_2',
		{ 'status' : 'P' } ),
	( 'pdkrun_test_data/minipyt/class_attr.test.test_1',
		{ 'status' : 'P' } ),
	( 'pdkrun_test_data/minipyt/class_attr.test',
		{ 'status' : 'P' } ),
	( 'pdkrun_test_data/minipyt/class_attr',
		{ 'status' : 'P' } ),
	( 'pdkrun_test_data/minipyt/disables.class_active.test1',
		{ 'status' : 'P' } ),
	( 'pdkrun_test_data/minipyt/disables.class_active.test2',
		{ 'status' : 'P' } ),
	( 'pdkrun_test_data/minipyt/disables.class_active.test3',
		{ 'status' : 'P' } ),
	( 'pdkrun_test_data/minipyt/disables.class_active',
		{ 'status' : 'P' } ),
	( 'pdkrun_test_data/minipyt/disables.class_disable',
		{ 'status' : 'D' } ),
	( 'pdkrun_test_data/minipyt/disables.class_partial.test1',
		{ 'status' : 'D' } ),
	( 'pdkrun_test_data/minipyt/disables.class_partial.test2',
		{ 'status' : 'D' } ),
	( 'pdkrun_test_data/minipyt/disables.class_partial.test3',
		{ 'status' : 'P' } ),
	( 'pdkrun_test_data/minipyt/disables.class_partial',
		{ 'status' : 'P' } ),
	( 'pdkrun_test_data/minipyt/disables.function_active',
		{ 'status' : 'P' } ),
	( 'pdkrun_test_data/minipyt/disables.function_disable',
		{ 'status' : 'D' } ),
	( 'pdkrun_test_data/minipyt/disables',
		{ 'status' : 'P' } ),
	( 'pdkrun_test_data/minipyt/function.test_p',
		{ 'status' : 'P' } ),
	( 'pdkrun_test_data/minipyt/function.test_f',
		{ 'status' : 'F' } ),
	( 'pdkrun_test_data/minipyt/function.test_e',
		{ 'status' : 'E' } ),
	( 'pdkrun_test_data/minipyt/function.minipyt_decorated',
		{ 'status' : 'P' } ),
	( 'pdkrun_test_data/minipyt/function.fn_with_tda',
		{ 'status' : 'P' } ),
	( 'pdkrun_test_data/minipyt/function.fn_with_tra',
		{ 'status' : 'P' } ),
	( 'pdkrun_test_data/minipyt/function.fn_with_attributes',
		{ 'status' : 'F' } ),
	( 'pdkrun_test_data/minipyt/function.fn_nose_decorated',
		{ 'status' : 'P' } ),
	( 'pdkrun_test_data/minipyt/function.test_nose_raises_does',
		{ 'status' : 'P' } ),
	( 'pdkrun_test_data/minipyt/function.test_nose_raises_not',
		{ 'status' : 'F' } ),
	( 'pdkrun_test_data/minipyt/function.test_nose_timed_asserts',
		{ 'status' : 'F' } ),
	( 'pdkrun_test_data/minipyt/function.test_nose_timed_exc',
		{ 'status' : 'E' } ),
	( 'pdkrun_test_data/minipyt/function.test_nose_timed_nok',
		{ 'status' : 'F' } ),
	( 'pdkrun_test_data/minipyt/function.test_nose_timed_ok',
		{ 'status' : 'P' } ),
	( 'pdkrun_test_data/minipyt/function',
		{ 'status' : 'P' } ),
	( 'pdkrun_test_data/minipyt/import_exception',
		{ 'status' : 'E' } ),
	( 'pdkrun_test_data/minipyt/import_fpe',
		{ 'status' : 'E' } ),
	( 'pdkrun_test_data/minipyt/import_syntax_error',
		{ 'status' : 'E' } ),
	( 'pdkrun_test_data/minipyt/nose_decorate.test_s1',
		{ 'status' : 'P' } ),
	( 'pdkrun_test_data/minipyt/nose_decorate.test_s2',
		{ 'status' : 'P' } ),
	( 'pdkrun_test_data/minipyt/nose_decorate.test_s3',
		{ 'status' : 'P' } ),
	( 'pdkrun_test_data/minipyt/nose_decorate.test_s4',
		{ 'status' : 'E' } ),
	( 'pdkrun_test_data/minipyt/nose_decorate.test_s5',
		{ 'status' : 'E' } ),
	( 'pdkrun_test_data/minipyt/nose_decorate.test_s6',
		{ 'status' : 'E' } ),
	( 'pdkrun_test_data/minipyt/nose_decorate.test_s7',
		{ 'status' : 'E' } ),
	( 'pdkrun_test_data/minipyt/nose_decorate.test_s8',
		{ 'status' : 'F' } ),
	( 'pdkrun_test_data/minipyt/nose_decorate.test_1',
		{ 'status' : 'F' } ),
	( 'pdkrun_test_data/minipyt/nose_decorate.test_2',
		{ 'status' : 'P' } ),
	( 'pdkrun_test_data/minipyt/nose_decorate',
		{ 'status' : 'P' } ),
	( 'pdkrun_test_data/minipyt/order.test_4.test_4_2',
		{ 'status' : 'P' } ),
	( 'pdkrun_test_data/minipyt/order.test_4.test_4_3',
		{ 'status' : 'P' } ),
	( 'pdkrun_test_data/minipyt/order.test_4.test_4_1',
		{ 'status' : 'P' } ),
	( 'pdkrun_test_data/minipyt/order.test_4',
		{ 'status' : 'P' } ),
	( 'pdkrun_test_data/minipyt/order.test_2',
		{ 'status' : 'P' } ),
	( 'pdkrun_test_data/minipyt/order.test_3',
		{ 'status' : 'P' } ),
	( 'pdkrun_test_data/minipyt/order.test_1',
		{ 'status' : 'P' } ),
	( 'pdkrun_test_data/minipyt/order',
		{ 'status' : 'P' } ),
]

test_in_db.perform_db_tests( test_in_db.query , expected_results )

