#! python

#
# pandokia - a test reporting and execution system
# Copyright 2009, Association of Universities for Research in Astronomy (AURA) 
#

# This is the entry point that "pdk run" uses to invoke the
# pandokia-enabled nose.

import sys
import pytest

# This is what you do if pandokia is not registering entry points for
# the plugins.  It is currently, using dorque_egg_info()
#sys.exit(pytest.main(['-p', 'pandokia.helpers.pytest_plugin'] + sys.argv[1:]))

sys.exit(pytest.main(sys.argv[1:]))

