#! python

#
# pandokia - a test reporting and execution system
# Copyright 2009, Association of Universities for Research in Astronomy (AURA) 
#

# This is the entry point for pandokia invoked as :
#   - a command line program
#   - a CGI in the context of a web server
#

import sys

# Invoke the actual entry point.
import pandokia.entry
sys.exit(pandokia.entry.run())
