#!/bin/sh
#
# This shell script exists only to collect the stdout/stderr so we can insert
# them into $PDK_LOG.  regress_helper executes a mix of python code and
# IRAF tasks -- it is not practical to try to make it collect all of its own
# stdout.  This script is not portable to Windows, but neither is IRAF, so it
# doesn't matter.
#

tmpfile=pdk.runner.tmp

tmpfile2=pdk.runner.2.tmp

rm -f $tmpfile
rm -f $tmpfile2

PDK_LOG=$tmpfile2 pdk_stsci_regress_helper > $tmpfile 2>&1

if [ -d $tmpfile2 ]
then
	cat $tmpfile2 >> $PDK_LOG
	( echo 'log:'
	sed 's/^/./' < $tmpfile
	echo ''
	echo END
	) >> $PDK_LOG
else
	(
	echo 'test_name='$PDK_TESTPREFIX/`basename $PDK_FILE .xml`
	echo 'status=E'
	echo 'end_time='`date +%s`
	echo '.pdk_stsci_regress_helper did not produce tmpfile2:'
	sed 's/^/./' < $tmpfile
	echo ''
	echo END
	) >> $PDK_LOG
fi

rm -f $tmpfile
rm -f $tmpfile2

