#!python

#
# pandokia - a test reporting and execution system
# Copyright 2010, Association of Universities for Research in Astronomy (AURA) 
#

import pandokia.helpers.filecomp as f

import sys
argv = sys.argv

okfh = open( argv[3], "a" )

f.check_file(name=argv[1], cmp=argv[2], okfh = okfh )

