#!/usr/stsci/pyssgdev/Python-2.5.4/bin/python

#
# pandokia - a test reporting and execution system
# Copyright 2009, Association of Universities for Research in Astronomy (AURA) 
#

# This script is the same as "pdk run", but pdkrun is such a common operation
# that I want to be able to type "!pdkr" at my shell.
#

# This ensures that we get the pandokia package that we expect.
# You cannot count on the _correct_ pandokia package being in the
# system site-packages or on PYTHONPATH.

PDK_DIR_HERE    # this will be edited by setup.py when you install
import sys
sys.path.insert(0, pdk_dir)

# import pandokia
# pandokia.select_config("configname")

# make it think we typed "pdk run".
sys.argv.insert(1,'run')

# Invoke the actual entry point.
import pandokia.entry
sys.exit(pandokia.entry.run())
