#!/bin/sh

version=`grep ^__version pandokia/__init__.py  | sed 's/^.*=//' | tr -d '" '`
echo Version $version

name=pandokia-$version

rm -rf $name $name.zip $name.tar

mkdir $name
find . -type f | grep -v '\.svn' | tar -c -f - -T - | ( cd $name ; tar xf - )

zip -q -r $name.zip $name
ls -l $name.zip

tar cfz $name.tar $name
ls -l $name.tar


